# https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/
version: '3.8'
services:
  jobcreator:
    build:
      context: .
      dockerfile: ./docker/jobcreator/Dockerfile
    depends_on:
      - jobmanager
    environment:
      - JOBS=
        org.example.BlockchainUnconfirmedTransactions
        org.example.BlockchainUnconfirmedTransactionsUsingTable
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  jobmanager:
    build:
      context: .
      dockerfile: ./docker/taskandjobmanager/Dockerfile
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    build:
      context: .
      dockerfile: ./docker/taskandjobmanager/Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2